In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import ast

In [2]:
zno_results = pd.read_csv('results/zno-results.csv',delimiter=',')
folktables_results = pd.read_csv('results/folktables-results.csv',delimiter=',')
students_loans_diabetes_results = pd.read_csv('results/students-loans-diabetes-results.csv',delimiter=',')

In [30]:
results_df_raw = pd.concat([zno_results, folktables_results, students_loans_diabetes_results], ignore_index=True, axis=0)

In [5]:
#results_df_raw = pd.read_csv('results/zno-sensitivty-analysis-results.csv',delimiter=',')

In [6]:
# Make it pretty

results_df = results_df_raw.copy()

def prettyify_dict(x):
    temp_dict = dict(sorted(ast.literal_eval(x).items()))
    temp_str = str(temp_dict)
    temp_str = temp_str.replace('{','')
    temp_str = temp_str.replace('}','')
    temp_str = temp_str.replace("'",'')
    temp_str = temp_str.replace(',',';')
    return temp_str

dataset_mapper = {'Ukr': 'EIE (Ukranian)',
                  'Hist': 'EIE (History)',
                  'Math': 'EIE (Math)',
                  'Phys': 'EIE (Physics)',
                  'Chem': 'EIE (Chemsitry)',
                  'Geo': 'EIE (Geography)',
                  'Eng': 'EIE (English)',
                  'Deu': 'EIE (German)',
                  'ACSEmployment': 'Folktables (Employment)',
                  'ACSIncome': 'Folktables (Income)',
                  'ACSPublicCoverage': 'Folktables (Public Medical Coverage)',
                  'ACSMobility': 'Folktables (Mobility)',
                  'ACSTravelTime': 'Folktables (Travel Time)',
                  'loans': 'Loan Assessment',
                  'diabetes': 'Diabetes Risk Assessment',
                  'students': 'Student Performance'}

sensitve_attr_mapper = {
                        'education': 'Education Level',
                        'parents_education': "Parent's Education Level"}


results_df['dataset'] = results_df['dataset'].map(dataset_mapper)
results_df['sensitive_attr'] = results_df['sensitive_attr'].replace(sensitve_attr_mapper)

results_df['sensitive_attr'] = results_df['sensitive_attr'].apply(lambda x: str(x).capitalize())

# After renames
results_df['group_dist'] = results_df['group_dist'].apply(prettyify_dict)
results_df['group_prev'] = results_df['group_prev'].apply(prettyify_dict)

# Lastly rename columns:
column_mapper = {'dataset': 'Dataset (Outcome)',
                 'sample_size': 'Number of Samples',
                 'overall_prev': 'Overall Prevelance (%)',
                 'sensitive_attr': 'Sensitive Attribute',
                 'group_dist': 'Group Distribution (%)',
                 'group_prev': 'Group Prevelance (%)',
                 'max_group_prev_diff': 'Maximum Group Prevelance Difference (%)'}

results_df.rename(columns=column_mapper, inplace=True)

In [7]:
results_df.head()

,Dataset (Outcome),Number of Samples,Overall Prevelance (%),Sensitive Attribute,Group Distribution (%),Group Prevelance (%),Maximum Group Prevelance Difference (%)
0,EIE (Ukranian),5777,7.34,Sex,Female: 51.96; Male: 48.04,Female: 4.26; Male: 10.67,6.41
1,EIE (Ukranian),5777,7.34,Territory,Rural: 25.34; Urban: 74.66,Rural: 10.38; Urban: 6.31,4.07
2,EIE (History),5982,17.99,Sex,Female: 54.35; Male: 45.65,Female: 14.43; Male: 22.23,7.80
3,EIE (History),5982,17.99,Territory,Rural: 29.69; Urban: 70.31,Rural: 20.21; Urban: 17.05,3.16
4,EIE (Math),7327,31.05,Sex,Female: 48.7; Male: 51.3,Female: 30.91; Male: 31.18,0.27

In [8]:
#results_df.to_csv('results/zno-sensitivty-analysis-results-formatted.csv',index=False)
results_df.to_csv('results/all_results.csv',index=False)

# Intersectionality

In [39]:
folktables_inter_results = pd.read_csv('results/folktables-intersectional-results.csv',delimiter=',')

In [40]:
folktables_inter_results['dataset'] = folktables_inter_results['dataset'].map(dataset_mapper)
folktables_inter_results['sensitive_attr'] = folktables_inter_results['sensitive_attr'].replace(sensitve_attr_mapper)

folktables_inter_results['sensitive_attr'] = folktables_inter_results['sensitive_attr'].apply(lambda x: str(x).capitalize())

# After renames
folktables_inter_results['group_dist'] = folktables_inter_results['group_dist'].apply(prettyify_dict)
folktables_inter_results['group_prev'] = folktables_inter_results['group_prev'].apply(prettyify_dict)

folktables_inter_results.rename(columns=column_mapper, inplace=True)

In [41]:
folktables_inter_results

,Dataset (Outcome),Number of Samples,Overall Prevelance (%),Sensitive Attribute,Group Distribution (%),Group Prevelance (%),Maximum Group Prevelance Difference (%)
0,Folktables (Employment),1970,46.45,Race and sex,Asian alone; Female: 4.52; Asian alone; Male: ...,Asian alone; Female: 46.07; Asian alone; Male:...,14.76
1,Folktables (Income),1031,41.51,Race and sex,Asian alone; Female: 4.46; Asian alone; Male: ...,Asian alone; Female: 39.13; Asian alone; Male:...,29.63
2,Folktables (Public Medical Coverage),1352,40.09,Race and sex,Asian alone; Female: 6.07; Asian alone; Male: ...,Asian alone; Female: 40.24; Asian alone; Male:...,20.64
3,Folktables (Mobility),1214,78.17,Race and sex,Asian alone; Female: 5.52; Asian alone; Male: ...,Asian alone; Female: 74.63; Asian alone; Male:...,7.19
4,Folktables (Travel Time),1824,53.78,Race and sex,Asian alone; Female: 4.5; Asian alone; Male: 4...,Asian alone; Female: 65.85; Asian alone; Male:...,23.89

In [42]:
folktables_inter_results.to_csv('results/inter_results.csv',index=False)